// utils
export const TOAST = 'TOAST';
export const OPEN_TOAST = 'OPEN_TOAST';
export const CLOSE_TOAST = 'CLOSE_TOAST';


// wallet
export const CREATE_WALLET = 'CREATE_WALLET';
export const ENCRYPT_WALLET = 'ENCRYPT_WALLET';
export const GET_WALLET_FROM_STORAGE = 'GET_WALLET_FROM_STORAGE';
export const DECRYPTE_WALLET = 'DECRYPTE_WALLET';


// account
export const GET_ADDRESS_INFO = 'GET_ADDRESS_INFO';
export const GET_ADDRESS_INFO_FROM_STORAGE = 'GET_ADDRESS_INFO_FROM_STORAGE';

